MyFinance/Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class ContaController : Controller
    {
        private IHttpContextAccessor HttpContextAccessor { get; set; }

        public ContaController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            int.TryParse(HttpContextAccessor.HttpContext.Session.GetString("IdUsuarioLogado"), out int id_usuario_logado);

            ViewBag.ListaConta = new ContaModel().GetContas(id_usuario_logado);
            return View();
        }

        [HttpGet]
        public IActionResult CriarConta(int? id)
        {
            if (id != null)
            {
                ViewBag.Registro = new ContaModel().CarregarRegistro(id);
            }

            return View();
        }

        [HttpPost]
        public IActionResult CriarConta(ContaModel contaModel)
        {
            if (ModelState.IsValid)
            {
                int.TryParse(HttpContextAccessor.HttpContext.Session.GetString("IdUsuarioLogado"), out int id_usuario_logado);


                if (contaModel.Id > 0)
                {
                    contaModel.Update();
                }
                else
                {
                    contaModel.Insert(id_usuario_logado);
                }
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult ExcluirConta(int id)
        {
            new ContaModel().Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

MyFinance/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Nome"] = new HomeModel().LerNomeUsuario();
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Ajuda()
        {
            return View();
        }
    }
}

MyFinance/Controllers/PlanoContaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class PlanoContaController : Controller
    {
        private IHttpContextAccessor HttpContextAccessor { get; set; }

        public PlanoContaController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            int.TryParse(HttpContextAccessor.HttpContext.Session.GetString("IdUsuarioLogado"), out int id_usuario_logado);

            ViewBag.ListaPlanoConta = new PlanoContaModel().GetPlanoContas(id_usuario_logado);
            return View();
        }

        [HttpGet]
        public IActionResult CriarPlanoConta(int? id)
        {
            if (id != null)
            {
                ViewBag.Registro = new PlanoContaModel().CarregarRegistro(id);
            }
            return View();
        }

        [HttpPost]
        public IActionResult CriarPlanoConta(PlanoContaModel planoContaModel)
        {
            if (ModelState.IsValid)
            {
                int.TryParse(HttpContextAccessor.HttpContext.Session.GetString("IdUsuarioLogado"), out int id_usuario_logado);


                if (planoContaModel.Id > 0)
                {
                    planoContaModel.Update();
                }
                else
                {
                    planoContaModel.Insert(id_usuario_logado);
                }

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult ExcluirPlanoConta(int id)
        {
            new PlanoContaModel().Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

MyFinance/Controllers/TransacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class TransacaoController : Controller
    {
        private IHttpContextAccessor HttpContextAccessor { get; set; }

        public TransacaoController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }


        public IActionResult Index()
        {
            int.TryParse(HttpContextAccessor.HttpContext.Session.GetString("IdUsuarioLogado"), out int id_usuario_logado);
            ViewBag.ListaTransacoes = new TransacaoModel().GetTransacoes(id_usuario_logado);
            return View();
        }
        [HttpPost]
        [HttpGet]
        public IActionResult Extrato(TransacaoModel transacao)
        {
            int.TryParse(HttpContextAccessor.HttpContext.Session.GetString("IdUsuarioLogado"), out int id_usuario_logado);

            ViewBag.ListaTransacao = transacao.GetTransacoes(id_usuario_logado);
            ViewBag.ListaConta = new ContaModel().GetContas(id_usuario_logado);
            return View();
        }

        [HttpGet]
        public IActionResult Dashboard()
        {
            int.TryParse(HttpContextAccessor.HttpContext.Session.GetString("IdUsuarioLogado"), out int id_usuario_logado);
            var listDashboard = new DashboardModel().GetDadosGraficoPie(id_usuario_logado);

            string valores = "";
            string labels = "";
            string cores = "";
            var random = new Random();
            foreach (var item in listDashboard)
            {
                var color = String.Format("#{0:X6}", random.Next(0x1000000)); // = "#A197B9"

                valores += $"{item.Total},";
                labels += $"'{item.Descricao}',";
                cores += $"'{color}',";
            }
            ViewBag.Valores = valores;
            ViewBag.Labels = labels;
            ViewBag.Cores = cores;


            return View();
        }

        [HttpGet]
        public IActionResult CriarTransacao(int? id)
        {
            int.TryParse(HttpContextAccessor.HttpContext.Session.GetString("IdUsuarioLogado"), out int id_usuario_logado);

            ViewBag.ListaContas = new ContaModel().GetContas(id_usuario_logado);
            ViewBag.ListaPlanoContas = new PlanoContaModel().GetPlanoContas(id_usuario_logado);

            if (id != null)
            {
                ViewBag.Registro = new TransacaoModel().CarregarRegistro(id);
            }

            return PartialView();
        }

        [HttpPost]
        public IActionResult CriarTransacao(TransacaoModel transacaoModel)
        {
            if (ModelState.IsValid)
            {
                int.TryParse(HttpContextAccessor.HttpContext.Session.GetString("IdUsuarioLogado"), out int id_usuario_logado);

                if (transacaoModel.Id > 0)
                {
                    transacaoModel.Update();
                }
                else
                {
                    transacaoModel.Insert();
                }
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult ExcluirTransacao(int id)
        {
            ViewBag.Registro = new TransacaoModel().CarregarRegistro(id);
            return PartialView();
        }

        public IActionResult Excluir(int id)
        {
            new TransacaoModel().Excluir(id);
            return RedirectToAction("Index");
        }

    }
}

MyFinance/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MyFinance/Views/Home/Ajuda.cshtml
@{
    ViewData["Title"] = "Ajuda";
}

<h2>Ajuda</h2>

MyFinance/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyFinance/Views/Home/Index.cshtml
<div class="row">
    <a asp-area="" asp-controller="Conta" asp-action="Index">
        <div class="col-lg-4 text-center">
            <img src="~/images/conta.png" width="35%" />
            <h3>Criar Conta</h3>
        </div>
    </a>
    <a asp-area="" asp-controller="PlanoConta" asp-action="Index">
        <div class="col-lg-4 text-center">
            <img src="~/images/planocontas.png" width="35%" />
            <h3>Plano de Contas</h3>
        </div>
    </a>

    <a asp-area="" asp-controller="Transacao" asp-action="Index">
        <div class="col-lg-4 text-center">
            <img src="~/images/registrar_transacao.png" width="35%" />
            <h3>Registrar Transação</h3>
        </div>
    </a>
</div>

<br /> <br /> <br />

<div class="row">
    <a asp-area="" asp-controller="Transacao" asp-action="Extrato">
        <div class="col-lg-4 text-center">
            <img src="~/images/extrato.png" width="35%" />
            <h3>Extrato</h3>
        </div>
    </a>
    <a asp-area="" asp-controller="Transacao" asp-action="Dashboard">
        <div class="col-lg-4 text-center">
            <img src="~/images/dashboard.png" width="35%" />
            <h3>Dashboard</h3>
        </div>
    </a>
    <a asp-area="" asp-controller="Home" asp-action="Ajuda">
        <div class="col-lg-4 text-center">
            <img src="~/images/ajuda.png" width="35%" />
            <h3>Ajuda</h3>
        </div>
    </a>
</div>